# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-28 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission',
        ),
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, to='rbac.Permission'),
        ),
    ]
